### ISSUE TITLE
Improve READMEs

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/GRASPA-benchmark#10]
We need to considerably improve the description of this repo, including:
- [x] description of the files
- [x] description of the executables
- [x] how to fill in the xml files to run the benchmark with the user's code
- [x] how to run the scripts
- [x] how to use Gitpod

**Comment by pattacini** [comment]
I've noticed how Gitpod is unable to render images correctly within the main README.md, as they're formatted with the resort to `html`. Here's a snapshot:

![Annotation 2019-08-22 140055](https://user-images.githubusercontent.com/3738070/63513173-c600b200-c4e5-11e9-8e8e-6403f1d76c93.jpg)

I'm wondering if it could be convenient to reserve the main README.md to contain only `how-to-install` instructions and move the rest to other files.

Alternatively, it may be worth publishing a small site with `gh-pages`, where images and whatsoever can be rendered nicely together with the video.

**Comment by giuliavezzani** [comment]
Mmmm, we could consider the idea to create also a website, but honestly, I'd leave the READMEs as they are. I think it's not a big issue if they are not rendered in the GitPod, whose aim is mostly to allow for code reproducibility and not to show the READMEs.

**Comment by pattacini** [comment]
I see your point, but aside from Gitpod, mine was more a suggestion to move the `how-to-collect-data` to secondary section to avoid cluttering the main README.md.

**Comment by giuliavezzani** [comment]
I see. The reason why I put it in the main README is that it's an information with high priority for the usability of the benchmark, given that we didn't have space to write it extensively in the paper. However, I can think of a way to make clear in the main README where to find the instruction on how to collect the data.

**Comment by pattacini** [comment]
Good 👍 
You could take inspiration from https://github.com/robotology/haptic-devices, where the section `Client Examples` is linked from within the main README.md but hosted separately in a subfolder.

**Comment by giuliavezzani** [comment]
Done :+1:

**Comment by fbottarel** [comment]
Every point in the list has been accounted for. Shall we close this?
