### ISSUE TITLE
Bump release 1.0

### ISSUE THREAD

**Issue by pattacini** [robotology/GRASPA-benchmark#13]
Let's create `release 1.0` for the code to stick out clearly to reflect what's claimed in the paper.

**Comment by giuliavezzani** [comment]
@pattacini I agree with this. I'll synchronize with @fbottarel at this regard.

**Comment by fbottarel** [comment]
I already wanted to polish up the code a bit, write the missing readme and push my own docker image as soon as the summer break would be over (i.e. in a couple of days).

**Comment by fbottarel** [comment]
Release v1.0 is online!
