### ISSUE TITLE
Provide utils for using the benchmark

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/GRASPA-benchmark#8]
Since we'll need to write some code to test the benchmark on our robots, it'd be useful to provide some utils (python based) that can help the user collect the data faster as well as parse and generate the files required by the benchmark.

**Comment by giuliavezzani** [comment]
I think we can close this, unless @fbottarel is planning to write something with ROS to use the benchmark on the Panda. [`GRASPA-test`](https://github.com/robotology-playground/GRASPA-test) has been extensively tested on the iCub and the READMEs are full of info.

**Comment by fbottarel** [comment]
I am not planning to write code to adapt the benchmark to ROS, at least not soon.  I guess we can close this for the time being.
